### ISSUE TITLE
Add "Night Mood" as a To-Do item

### ISSUE THREAD

**Issue by peterdanwan** [tawhidmonowar/WebCapture#40]
This is to add "Night Mood" as a new To-Do item in the `README.md` file.
![image](https://github.com/user-attachments/assets/597e8fc0-4e3c-40f2-9b04-3bbc00ca9078)

**Comment by tawhidmonowar** [comment]
@peterdanwan it will be great if you can improve any other thing

**Comment by peterdanwan** [comment]
Hi @tawhidmonowar I'll see what I can do! Can we close this issue for now?
