### ISSUE TITLE
Add "get it on IzzyOnDroid" badge, mentioed here. 

### ISSUE THREAD

**Issue by tawhidmonowar** [tawhidmonowar/WebCapture#42]
Add it below web Capture short description, if you face any problem don't forget to comment here, thank you.

              @tawhidmonowar your app is [live at IzzyOnDroid with the new appId](https://apt.izzysoft.de/packages/com.tawhid.webcapture) and shows as [Reproducible Build](https://reproducible-builds.org/) – so be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley: The only open issue from our end (at IzzyOnDroid) is the signing block blob, which still needs fixing ([see here](https://github.com/tawhidmonowar/WebCapture/issues/35#issuecomment-2328186949) for details):

![image](https://github.com/user-attachments/assets/08bd46b2-33b2-42ee-9e32-d46e0dd28d4b)

@licaon-kter any other issues you see amiss for F-Droid?

_Originally posted by @IzzySoft in https://github.com/tawhidmonowar/WebCapture/issues/35#issuecomment-2332609150_

**Comment by Kishore1K** [comment]
Hi ,is this Issue still open so that i can contribute

**Comment by licaon-kter** [comment]
I'll comment in the other issue when ready

**Comment by tawhidmonowar** [comment]
@licaon-kter it is ready, here is the download link "https://apt.izzysoft.de/fdroid/index/apk/com.tawhid.webcapture"
