### ISSUE TITLE
Help me to update github page 

### ISSUE THREAD

**Issue by tawhidmonowar** [tawhidmonowar/WebCapture#45]
Help me to update the github page for this app, folder structure index.html in root folder and all the other file in this "[githubpage](https://github.com/tawhidmonowar/WebCapture/tree/main/githubpage)"  Folder.

**Comment by lucasackerberg** [comment]
https://github.com/tawhidmonowar/WebCapture/pull/46

Take a look at my PR. Let me know if you want more elaborate help!

**Comment by tawhidmonowar** [comment]
Thank you for PR, can you have a look at https://tawhidmonowar.github.io/WebCapture/
there is something wrong! also can you update the button link? and remove fdroid and add IzzyOnDroid and update the badges remove unnecessary badges

**Comment by tawhidmonowar** [comment]
Screenshots images are available here https://github.com/tawhidmonowar/WebCapture/tree/main/fastlane/metadata/android/en-US/images/phoneScreenshots

**Comment by lucasackerberg** [comment]
Will be back in a few hours to have a look!

**Comment by lucasackerberg** [comment]
> Screenshots images are available here https://github.com/tawhidmonowar/WebCapture/tree/main/fastlane/metadata/android/en-US/images/phoneScreenshots

https://github.com/tawhidmonowar/WebCapture/pull/47

**Comment by tawhidmonowar** [comment]
#47 thanks, it looks great.
